# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(choices=[('A', 'Client A'), ('B', 'Client B'), ('C', 'Client A')], max_length=1)),
                ('client_priority', models.IntegerField()),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('ticket_url', models.URLField()),
                ('prod_area', models.CharField(choices=[('P', 'Policies'), ('B', 'Billing'), ('C', 'Claims'), ('R', 'Reports')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
