# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='client',
            field=models.CharField(choices=[('A', 'Client A'), ('B', 'Client B'), ('C', 'Client C')], max_length=1),
        ),
    ]
